// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DateTimeDemo2.proto

package com.google.protobuf.dotnettype;

public final class DateTimeDemo2OuterClass {
  private DateTimeDemo2OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DateTimeDemo2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:DateTimeDemo2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string title = 1;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required DateTime dateTimeValue = 2;</code>
     */
    boolean hasDateTimeValue();
    /**
     * <code>required DateTime dateTimeValue = 2;</code>
     */
    java.util.Calendar getDateTimeValue();
  }
  /**
   * Protobuf type {@code DateTimeDemo2}
   */
  public  static final class DateTimeDemo2 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DateTimeDemo2)
      DateTimeDemo2OrBuilder {
    // Use DateTimeDemo2.newBuilder() to construct.
    private DateTimeDemo2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DateTimeDemo2() {
      title_ = "";
      dateTimeValue_ = com.google.protobuf.dotnettype.DateTimes.defaultCalendar();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DateTimeDemo2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              title_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              dateTimeValue_ = input.readDateTime();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.internal_static_DateTimeDemo2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.internal_static_DateTimeDemo2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2.class, com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>required string title = 1;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATETIMEVALUE_FIELD_NUMBER = 2;
    private java.util.Calendar dateTimeValue_;
    /**
     * <code>required DateTime dateTimeValue = 2;</code>
     */
    public boolean hasDateTimeValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required DateTime dateTimeValue = 2;</code>
     */
    public java.util.Calendar getDateTimeValue() {
      return dateTimeValue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDateTimeValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, title_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDateTime(2, dateTimeValue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, title_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDateTimeSize(2, dateTimeValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2)) {
        return super.equals(obj);
      }
      com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 other = (com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2) obj;

      boolean result = true;
      result = result && (hasTitle() == other.hasTitle());
      if (hasTitle()) {
        result = result && getTitle()
            .equals(other.getTitle());
      }
      result = result && (hasDateTimeValue() == other.hasDateTimeValue());
      if (hasDateTimeValue()) {
        result = result && getDateTimeValue()
            .equals(other.getDateTimeValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasDateTimeValue()) {
        hash = (37 * hash) + DATETIMEVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getDateTimeValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DateTimeDemo2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DateTimeDemo2)
        com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.internal_static_DateTimeDemo2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.internal_static_DateTimeDemo2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2.class, com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2.Builder.class);
      }

      // Construct using com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dateTimeValue_ = com.google.protobuf.dotnettype.DateTimes.defaultCalendar();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.internal_static_DateTimeDemo2_descriptor;
      }

      public com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 getDefaultInstanceForType() {
        return com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2.getDefaultInstance();
      }

      public com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 build() {
        com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 buildPartial() {
        com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 result = new com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dateTimeValue_ = dateTimeValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2) {
          return mergeFrom((com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 other) {
        if (other == com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          bitField0_ |= 0x00000001;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasDateTimeValue()) {
          setDateTimeValue(other.getDateTimeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTitle()) {
          return false;
        }
        if (!hasDateTimeValue()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 1;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }

      private java.util.Calendar dateTimeValue_ = com.google.protobuf.dotnettype.DateTimes.defaultCalendar();
      /**
       * <code>required DateTime dateTimeValue = 2;</code>
       */
      public boolean hasDateTimeValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required DateTime dateTimeValue = 2;</code>
       */
      public java.util.Calendar getDateTimeValue() {
        return dateTimeValue_;
      }
      /**
       * <code>required DateTime dateTimeValue = 2;</code>
       */
      public Builder setDateTimeValue(java.util.Calendar value) {
        bitField0_ |= 0x00000002;
        dateTimeValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required DateTime dateTimeValue = 2;</code>
       */
      public Builder clearDateTimeValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dateTimeValue_ = com.google.protobuf.dotnettype.DateTimes.defaultCalendar();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DateTimeDemo2)
    }

    // @@protoc_insertion_point(class_scope:DateTimeDemo2)
    private static final com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2();
    }

    public static com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DateTimeDemo2>
        PARSER = new com.google.protobuf.AbstractParser<DateTimeDemo2>() {
      public DateTimeDemo2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DateTimeDemo2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DateTimeDemo2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DateTimeDemo2> getParserForType() {
      return PARSER;
    }

    public com.google.protobuf.dotnettype.DateTimeDemo2OuterClass.DateTimeDemo2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DateTimeDemo2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DateTimeDemo2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DateTimeDemo2.proto\032\020dotnettype.proto\"" +
      "5\n\rDateTimeDemo2\022\r\n\005title\030\001 \002(\t\022\025\n\rdateT" +
      "imeValue\030\002 \002(\023B \n\036com.google.protobuf.do" +
      "tnettype"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.dotnettype.DotNetTypeProtos.getDescriptor(),
        }, assigner);
    internal_static_DateTimeDemo2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DateTimeDemo2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DateTimeDemo2_descriptor,
        new java.lang.String[] { "Title", "DateTimeValue", });
    com.google.protobuf.dotnettype.DotNetTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
