// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DateTimeDemo.proto

package com.google.protobuf.util;

public final class DateTimeDemoOuterClass {
  private DateTimeDemoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DateTimeDemoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DateTimeDemo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string title = 1;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
     */
    boolean hasDateTimeValue();
    /**
     * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
     */
    com.google.protobuf.DateTime getDateTimeValue();
    /**
     * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
     */
    com.google.protobuf.DateTimeOrBuilder getDateTimeValueOrBuilder();
  }
  /**
   * Protobuf type {@code DateTimeDemo}
   */
  public  static final class DateTimeDemo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DateTimeDemo)
      DateTimeDemoOrBuilder {
    // Use DateTimeDemo.newBuilder() to construct.
    private DateTimeDemo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DateTimeDemo() {
      title_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DateTimeDemo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              title_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.DateTime.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = dateTimeValue_.toBuilder();
              }
              dateTimeValue_ = input.readMessage(com.google.protobuf.DateTime.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dateTimeValue_);
                dateTimeValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.util.DateTimeDemoOuterClass.internal_static_DateTimeDemo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.util.DateTimeDemoOuterClass.internal_static_DateTimeDemo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo.class, com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>required string title = 1;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATETIMEVALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.DateTime dateTimeValue_;
    /**
     * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
     */
    public boolean hasDateTimeValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
     */
    public com.google.protobuf.DateTime getDateTimeValue() {
      return dateTimeValue_ == null ? com.google.protobuf.DateTime.getDefaultInstance() : dateTimeValue_;
    }
    /**
     * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
     */
    public com.google.protobuf.DateTimeOrBuilder getDateTimeValueOrBuilder() {
      return dateTimeValue_ == null ? com.google.protobuf.DateTime.getDefaultInstance() : dateTimeValue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDateTimeValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, title_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getDateTimeValue());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, title_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDateTimeValue());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo)) {
        return super.equals(obj);
      }
      com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo other = (com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo) obj;

      boolean result = true;
      result = result && (hasTitle() == other.hasTitle());
      if (hasTitle()) {
        result = result && getTitle()
            .equals(other.getTitle());
      }
      result = result && (hasDateTimeValue() == other.hasDateTimeValue());
      if (hasDateTimeValue()) {
        result = result && getDateTimeValue()
            .equals(other.getDateTimeValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasDateTimeValue()) {
        hash = (37 * hash) + DATETIMEVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getDateTimeValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DateTimeDemo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DateTimeDemo)
        com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.util.DateTimeDemoOuterClass.internal_static_DateTimeDemo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.util.DateTimeDemoOuterClass.internal_static_DateTimeDemo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo.class, com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo.Builder.class);
      }

      // Construct using com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDateTimeValueFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dateTimeValueBuilder_ == null) {
          dateTimeValue_ = null;
        } else {
          dateTimeValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.util.DateTimeDemoOuterClass.internal_static_DateTimeDemo_descriptor;
      }

      public com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo getDefaultInstanceForType() {
        return com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo.getDefaultInstance();
      }

      public com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo build() {
        com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo buildPartial() {
        com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo result = new com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (dateTimeValueBuilder_ == null) {
          result.dateTimeValue_ = dateTimeValue_;
        } else {
          result.dateTimeValue_ = dateTimeValueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo) {
          return mergeFrom((com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo other) {
        if (other == com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          bitField0_ |= 0x00000001;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasDateTimeValue()) {
          mergeDateTimeValue(other.getDateTimeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTitle()) {
          return false;
        }
        if (!hasDateTimeValue()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 1;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.DateTime dateTimeValue_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DateTime, com.google.protobuf.DateTime.Builder, com.google.protobuf.DateTimeOrBuilder> dateTimeValueBuilder_;
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      public boolean hasDateTimeValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      public com.google.protobuf.DateTime getDateTimeValue() {
        if (dateTimeValueBuilder_ == null) {
          return dateTimeValue_ == null ? com.google.protobuf.DateTime.getDefaultInstance() : dateTimeValue_;
        } else {
          return dateTimeValueBuilder_.getMessage();
        }
      }
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      public Builder setDateTimeValue(com.google.protobuf.DateTime value) {
        if (dateTimeValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateTimeValue_ = value;
          onChanged();
        } else {
          dateTimeValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      public Builder setDateTimeValue(
          com.google.protobuf.DateTime.Builder builderForValue) {
        if (dateTimeValueBuilder_ == null) {
          dateTimeValue_ = builderForValue.build();
          onChanged();
        } else {
          dateTimeValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      public Builder mergeDateTimeValue(com.google.protobuf.DateTime value) {
        if (dateTimeValueBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              dateTimeValue_ != null &&
              dateTimeValue_ != com.google.protobuf.DateTime.getDefaultInstance()) {
            dateTimeValue_ =
              com.google.protobuf.DateTime.newBuilder(dateTimeValue_).mergeFrom(value).buildPartial();
          } else {
            dateTimeValue_ = value;
          }
          onChanged();
        } else {
          dateTimeValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      public Builder clearDateTimeValue() {
        if (dateTimeValueBuilder_ == null) {
          dateTimeValue_ = null;
          onChanged();
        } else {
          dateTimeValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      public com.google.protobuf.DateTime.Builder getDateTimeValueBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDateTimeValueFieldBuilder().getBuilder();
      }
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      public com.google.protobuf.DateTimeOrBuilder getDateTimeValueOrBuilder() {
        if (dateTimeValueBuilder_ != null) {
          return dateTimeValueBuilder_.getMessageOrBuilder();
        } else {
          return dateTimeValue_ == null ?
              com.google.protobuf.DateTime.getDefaultInstance() : dateTimeValue_;
        }
      }
      /**
       * <code>required .google.protobuf.DateTime dateTimeValue = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DateTime, com.google.protobuf.DateTime.Builder, com.google.protobuf.DateTimeOrBuilder> 
          getDateTimeValueFieldBuilder() {
        if (dateTimeValueBuilder_ == null) {
          dateTimeValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DateTime, com.google.protobuf.DateTime.Builder, com.google.protobuf.DateTimeOrBuilder>(
                  getDateTimeValue(),
                  getParentForChildren(),
                  isClean());
          dateTimeValue_ = null;
        }
        return dateTimeValueBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DateTimeDemo)
    }

    // @@protoc_insertion_point(class_scope:DateTimeDemo)
    private static final com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo();
    }

    public static com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DateTimeDemo>
        PARSER = new com.google.protobuf.AbstractParser<DateTimeDemo>() {
      public DateTimeDemo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DateTimeDemo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DateTimeDemo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DateTimeDemo> getParserForType() {
      return PARSER;
    }

    public com.google.protobuf.util.DateTimeDemoOuterClass.DateTimeDemo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DateTimeDemo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DateTimeDemo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022DateTimeDemo.proto\032\036google/protobuf/da" +
      "tetime.proto\"O\n\014DateTimeDemo\022\r\n\005title\030\001 " +
      "\002(\t\0220\n\rdateTimeValue\030\002 \002(\0132\031.google.prot" +
      "obuf.DateTimeB\032\n\030com.google.protobuf.uti" +
      "l"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DateTimeProto.getDescriptor(),
        }, assigner);
    internal_static_DateTimeDemo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DateTimeDemo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DateTimeDemo_descriptor,
        new java.lang.String[] { "Title", "DateTimeValue", });
    com.google.protobuf.DateTimeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
