// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DecimalDemo.proto

package com.google.protobuf.util;

public final class DecimalDemoOuterClass {
  private DecimalDemoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DecimalDemoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DecimalDemo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string title = 1;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
     */
    boolean hasDecimalValue();
    /**
     * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
     */
    com.google.protobuf.Decimal getDecimalValue();
    /**
     * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
     */
    com.google.protobuf.DecimalOrBuilder getDecimalValueOrBuilder();
  }
  /**
   * Protobuf type {@code DecimalDemo}
   */
  public  static final class DecimalDemo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DecimalDemo)
      DecimalDemoOrBuilder {
    // Use DecimalDemo.newBuilder() to construct.
    private DecimalDemo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DecimalDemo() {
      title_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DecimalDemo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              title_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.Decimal.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = decimalValue_.toBuilder();
              }
              decimalValue_ = input.readMessage(com.google.protobuf.Decimal.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(decimalValue_);
                decimalValue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.util.DecimalDemoOuterClass.internal_static_DecimalDemo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.util.DecimalDemoOuterClass.internal_static_DecimalDemo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo.class, com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>required string title = 1;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DECIMALVALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.Decimal decimalValue_;
    /**
     * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
     */
    public boolean hasDecimalValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
     */
    public com.google.protobuf.Decimal getDecimalValue() {
      return decimalValue_ == null ? com.google.protobuf.Decimal.getDefaultInstance() : decimalValue_;
    }
    /**
     * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
     */
    public com.google.protobuf.DecimalOrBuilder getDecimalValueOrBuilder() {
      return decimalValue_ == null ? com.google.protobuf.Decimal.getDefaultInstance() : decimalValue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDecimalValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, title_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getDecimalValue());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, title_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDecimalValue());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo)) {
        return super.equals(obj);
      }
      com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo other = (com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo) obj;

      boolean result = true;
      result = result && (hasTitle() == other.hasTitle());
      if (hasTitle()) {
        result = result && getTitle()
            .equals(other.getTitle());
      }
      result = result && (hasDecimalValue() == other.hasDecimalValue());
      if (hasDecimalValue()) {
        result = result && getDecimalValue()
            .equals(other.getDecimalValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasDecimalValue()) {
        hash = (37 * hash) + DECIMALVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getDecimalValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DecimalDemo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DecimalDemo)
        com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.util.DecimalDemoOuterClass.internal_static_DecimalDemo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.util.DecimalDemoOuterClass.internal_static_DecimalDemo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo.class, com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo.Builder.class);
      }

      // Construct using com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDecimalValueFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (decimalValueBuilder_ == null) {
          decimalValue_ = null;
        } else {
          decimalValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.util.DecimalDemoOuterClass.internal_static_DecimalDemo_descriptor;
      }

      public com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo getDefaultInstanceForType() {
        return com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo.getDefaultInstance();
      }

      public com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo build() {
        com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo buildPartial() {
        com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo result = new com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (decimalValueBuilder_ == null) {
          result.decimalValue_ = decimalValue_;
        } else {
          result.decimalValue_ = decimalValueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo) {
          return mergeFrom((com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo other) {
        if (other == com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo.getDefaultInstance()) return this;
        if (other.hasTitle()) {
          bitField0_ |= 0x00000001;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasDecimalValue()) {
          mergeDecimalValue(other.getDecimalValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTitle()) {
          return false;
        }
        if (!hasDecimalValue()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 1;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Decimal decimalValue_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Decimal, com.google.protobuf.Decimal.Builder, com.google.protobuf.DecimalOrBuilder> decimalValueBuilder_;
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      public boolean hasDecimalValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      public com.google.protobuf.Decimal getDecimalValue() {
        if (decimalValueBuilder_ == null) {
          return decimalValue_ == null ? com.google.protobuf.Decimal.getDefaultInstance() : decimalValue_;
        } else {
          return decimalValueBuilder_.getMessage();
        }
      }
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      public Builder setDecimalValue(com.google.protobuf.Decimal value) {
        if (decimalValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          decimalValue_ = value;
          onChanged();
        } else {
          decimalValueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      public Builder setDecimalValue(
          com.google.protobuf.Decimal.Builder builderForValue) {
        if (decimalValueBuilder_ == null) {
          decimalValue_ = builderForValue.build();
          onChanged();
        } else {
          decimalValueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      public Builder mergeDecimalValue(com.google.protobuf.Decimal value) {
        if (decimalValueBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              decimalValue_ != null &&
              decimalValue_ != com.google.protobuf.Decimal.getDefaultInstance()) {
            decimalValue_ =
              com.google.protobuf.Decimal.newBuilder(decimalValue_).mergeFrom(value).buildPartial();
          } else {
            decimalValue_ = value;
          }
          onChanged();
        } else {
          decimalValueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      public Builder clearDecimalValue() {
        if (decimalValueBuilder_ == null) {
          decimalValue_ = null;
          onChanged();
        } else {
          decimalValueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      public com.google.protobuf.Decimal.Builder getDecimalValueBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getDecimalValueFieldBuilder().getBuilder();
      }
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      public com.google.protobuf.DecimalOrBuilder getDecimalValueOrBuilder() {
        if (decimalValueBuilder_ != null) {
          return decimalValueBuilder_.getMessageOrBuilder();
        } else {
          return decimalValue_ == null ?
              com.google.protobuf.Decimal.getDefaultInstance() : decimalValue_;
        }
      }
      /**
       * <code>required .google.protobuf.Decimal decimalValue = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Decimal, com.google.protobuf.Decimal.Builder, com.google.protobuf.DecimalOrBuilder> 
          getDecimalValueFieldBuilder() {
        if (decimalValueBuilder_ == null) {
          decimalValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Decimal, com.google.protobuf.Decimal.Builder, com.google.protobuf.DecimalOrBuilder>(
                  getDecimalValue(),
                  getParentForChildren(),
                  isClean());
          decimalValue_ = null;
        }
        return decimalValueBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DecimalDemo)
    }

    // @@protoc_insertion_point(class_scope:DecimalDemo)
    private static final com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo();
    }

    public static com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DecimalDemo>
        PARSER = new com.google.protobuf.AbstractParser<DecimalDemo>() {
      public DecimalDemo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DecimalDemo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DecimalDemo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DecimalDemo> getParserForType() {
      return PARSER;
    }

    public com.google.protobuf.util.DecimalDemoOuterClass.DecimalDemo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DecimalDemo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DecimalDemo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DecimalDemo.proto\032\035google/protobuf/dec" +
      "imal.proto\"L\n\013DecimalDemo\022\r\n\005title\030\001 \002(\t" +
      "\022.\n\014decimalValue\030\002 \002(\0132\030.google.protobuf" +
      ".DecimalB\032\n\030com.google.protobuf.util"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DecimalProto.getDescriptor(),
        }, assigner);
    internal_static_DecimalDemo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DecimalDemo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DecimalDemo_descriptor,
        new java.lang.String[] { "Title", "DecimalValue", });
    com.google.protobuf.DecimalProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
