// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoList.proto

package com.google.protobuf.list;

public final class DemoListOuterClass {
  private DemoListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DemoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Demo value = 1;</code>
     */
    java.util.List<com.google.protobuf.list.DemoOuterClass.Demo> 
        getValueList();
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    com.google.protobuf.list.DemoOuterClass.Demo getValue(int index);
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    int getValueCount();
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    java.util.List<? extends com.google.protobuf.list.DemoOuterClass.DemoOrBuilder> 
        getValueOrBuilderList();
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    com.google.protobuf.list.DemoOuterClass.DemoOrBuilder getValueOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DemoList}
   */
  public  static final class DemoList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DemoList)
      DemoListOrBuilder {
    // Use DemoList.newBuilder() to construct.
    private DemoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DemoList() {
      value_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                value_ = new java.util.ArrayList<com.google.protobuf.list.DemoOuterClass.Demo>();
                mutable_bitField0_ |= 0x00000001;
              }
              value_.add(
                  input.readMessage(com.google.protobuf.list.DemoOuterClass.Demo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = java.util.Collections.unmodifiableList(value_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.list.DemoListOuterClass.internal_static_DemoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.list.DemoListOuterClass.internal_static_DemoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.list.DemoListOuterClass.DemoList.class, com.google.protobuf.list.DemoListOuterClass.DemoList.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.list.DemoOuterClass.Demo> value_;
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    public java.util.List<com.google.protobuf.list.DemoOuterClass.Demo> getValueList() {
      return value_;
    }
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    public java.util.List<? extends com.google.protobuf.list.DemoOuterClass.DemoOrBuilder> 
        getValueOrBuilderList() {
      return value_;
    }
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    public com.google.protobuf.list.DemoOuterClass.Demo getValue(int index) {
      return value_.get(index);
    }
    /**
     * <code>repeated .Demo value = 1;</code>
     */
    public com.google.protobuf.list.DemoOuterClass.DemoOrBuilder getValueOrBuilder(
        int index) {
      return value_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getValueCount(); i++) {
        if (!getValue(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < value_.size(); i++) {
        output.writeMessage(1, value_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < value_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, value_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.list.DemoListOuterClass.DemoList)) {
        return super.equals(obj);
      }
      com.google.protobuf.list.DemoListOuterClass.DemoList other = (com.google.protobuf.list.DemoListOuterClass.DemoList) obj;

      boolean result = true;
      result = result && getValueList()
          .equals(other.getValueList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getValueCount() > 0) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValueList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.list.DemoListOuterClass.DemoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.list.DemoListOuterClass.DemoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DemoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DemoList)
        com.google.protobuf.list.DemoListOuterClass.DemoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.list.DemoListOuterClass.internal_static_DemoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.list.DemoListOuterClass.internal_static_DemoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.list.DemoListOuterClass.DemoList.class, com.google.protobuf.list.DemoListOuterClass.DemoList.Builder.class);
      }

      // Construct using com.google.protobuf.list.DemoListOuterClass.DemoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getValueFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (valueBuilder_ == null) {
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          valueBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.list.DemoListOuterClass.internal_static_DemoList_descriptor;
      }

      public com.google.protobuf.list.DemoListOuterClass.DemoList getDefaultInstanceForType() {
        return com.google.protobuf.list.DemoListOuterClass.DemoList.getDefaultInstance();
      }

      public com.google.protobuf.list.DemoListOuterClass.DemoList build() {
        com.google.protobuf.list.DemoListOuterClass.DemoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.list.DemoListOuterClass.DemoList buildPartial() {
        com.google.protobuf.list.DemoListOuterClass.DemoList result = new com.google.protobuf.list.DemoListOuterClass.DemoList(this);
        int from_bitField0_ = bitField0_;
        if (valueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            value_ = java.util.Collections.unmodifiableList(value_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.list.DemoListOuterClass.DemoList) {
          return mergeFrom((com.google.protobuf.list.DemoListOuterClass.DemoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.list.DemoListOuterClass.DemoList other) {
        if (other == com.google.protobuf.list.DemoListOuterClass.DemoList.getDefaultInstance()) return this;
        if (valueBuilder_ == null) {
          if (!other.value_.isEmpty()) {
            if (value_.isEmpty()) {
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureValueIsMutable();
              value_.addAll(other.value_);
            }
            onChanged();
          }
        } else {
          if (!other.value_.isEmpty()) {
            if (valueBuilder_.isEmpty()) {
              valueBuilder_.dispose();
              valueBuilder_ = null;
              value_ = other.value_;
              bitField0_ = (bitField0_ & ~0x00000001);
              valueBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getValueFieldBuilder() : null;
            } else {
              valueBuilder_.addAllMessages(other.value_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getValueCount(); i++) {
          if (!getValue(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.list.DemoListOuterClass.DemoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.list.DemoListOuterClass.DemoList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.list.DemoOuterClass.Demo> value_ =
        java.util.Collections.emptyList();
      private void ensureValueIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          value_ = new java.util.ArrayList<com.google.protobuf.list.DemoOuterClass.Demo>(value_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.list.DemoOuterClass.Demo, com.google.protobuf.list.DemoOuterClass.Demo.Builder, com.google.protobuf.list.DemoOuterClass.DemoOrBuilder> valueBuilder_;

      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public java.util.List<com.google.protobuf.list.DemoOuterClass.Demo> getValueList() {
        if (valueBuilder_ == null) {
          return java.util.Collections.unmodifiableList(value_);
        } else {
          return valueBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public int getValueCount() {
        if (valueBuilder_ == null) {
          return value_.size();
        } else {
          return valueBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public com.google.protobuf.list.DemoOuterClass.Demo getValue(int index) {
        if (valueBuilder_ == null) {
          return value_.get(index);
        } else {
          return valueBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder setValue(
          int index, com.google.protobuf.list.DemoOuterClass.Demo value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueIsMutable();
          value_.set(index, value);
          onChanged();
        } else {
          valueBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder setValue(
          int index, com.google.protobuf.list.DemoOuterClass.Demo.Builder builderForValue) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          value_.set(index, builderForValue.build());
          onChanged();
        } else {
          valueBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder addValue(com.google.protobuf.list.DemoOuterClass.Demo value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueIsMutable();
          value_.add(value);
          onChanged();
        } else {
          valueBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder addValue(
          int index, com.google.protobuf.list.DemoOuterClass.Demo value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureValueIsMutable();
          value_.add(index, value);
          onChanged();
        } else {
          valueBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder addValue(
          com.google.protobuf.list.DemoOuterClass.Demo.Builder builderForValue) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          value_.add(builderForValue.build());
          onChanged();
        } else {
          valueBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder addValue(
          int index, com.google.protobuf.list.DemoOuterClass.Demo.Builder builderForValue) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          value_.add(index, builderForValue.build());
          onChanged();
        } else {
          valueBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder addAllValue(
          java.lang.Iterable<? extends com.google.protobuf.list.DemoOuterClass.Demo> values) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, value_);
          onChanged();
        } else {
          valueBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          valueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public Builder removeValue(int index) {
        if (valueBuilder_ == null) {
          ensureValueIsMutable();
          value_.remove(index);
          onChanged();
        } else {
          valueBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public com.google.protobuf.list.DemoOuterClass.Demo.Builder getValueBuilder(
          int index) {
        return getValueFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public com.google.protobuf.list.DemoOuterClass.DemoOrBuilder getValueOrBuilder(
          int index) {
        if (valueBuilder_ == null) {
          return value_.get(index);  } else {
          return valueBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public java.util.List<? extends com.google.protobuf.list.DemoOuterClass.DemoOrBuilder> 
           getValueOrBuilderList() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(value_);
        }
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public com.google.protobuf.list.DemoOuterClass.Demo.Builder addValueBuilder() {
        return getValueFieldBuilder().addBuilder(
            com.google.protobuf.list.DemoOuterClass.Demo.getDefaultInstance());
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public com.google.protobuf.list.DemoOuterClass.Demo.Builder addValueBuilder(
          int index) {
        return getValueFieldBuilder().addBuilder(
            index, com.google.protobuf.list.DemoOuterClass.Demo.getDefaultInstance());
      }
      /**
       * <code>repeated .Demo value = 1;</code>
       */
      public java.util.List<com.google.protobuf.list.DemoOuterClass.Demo.Builder> 
           getValueBuilderList() {
        return getValueFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.list.DemoOuterClass.Demo, com.google.protobuf.list.DemoOuterClass.Demo.Builder, com.google.protobuf.list.DemoOuterClass.DemoOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.list.DemoOuterClass.Demo, com.google.protobuf.list.DemoOuterClass.Demo.Builder, com.google.protobuf.list.DemoOuterClass.DemoOrBuilder>(
                  value_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DemoList)
    }

    // @@protoc_insertion_point(class_scope:DemoList)
    private static final com.google.protobuf.list.DemoListOuterClass.DemoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.list.DemoListOuterClass.DemoList();
    }

    public static com.google.protobuf.list.DemoListOuterClass.DemoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DemoList>
        PARSER = new com.google.protobuf.AbstractParser<DemoList>() {
      public DemoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DemoList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoList> getParserForType() {
      return PARSER;
    }

    public com.google.protobuf.list.DemoListOuterClass.DemoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DemoList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DemoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016DemoList.proto\032\ndemo.proto\" \n\010DemoList" +
      "\022\024\n\005value\030\001 \003(\0132\005.DemoB\032\n\030com.google.pro" +
      "tobuf.list"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.list.DemoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_DemoList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DemoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DemoList_descriptor,
        new java.lang.String[] { "Value", });
    com.google.protobuf.list.DemoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
