// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NestedMapDemo3.proto

package com.google.protobuf.list;

public final class NestedMapDemo3 {
  private NestedMapDemo3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NestedMapDemoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NestedMapDemo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */
    int getMetadataCount();
    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */
    boolean containsMetadata(
        int key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>>
    getMetadata();
    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */
    java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>>
    getMetadataMap();
    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */

    java.util.Map<java.lang.Integer, java.lang.Integer> getMetadataOrDefault(
        int key,
        java.util.Map<java.lang.Integer, java.lang.Integer> defaultValue);
    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */

    java.util.Map<java.lang.Integer, java.lang.Integer> getMetadataOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code NestedMapDemo}
   */
  public  static final class NestedMapDemo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NestedMapDemo)
      NestedMapDemoOrBuilder {
    // Use NestedMapDemo.newBuilder() to construct.
    private NestedMapDemo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NestedMapDemo() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NestedMapDemo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                metadata_ = com.google.protobuf.MapField.newMapField(
                    MetadataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>>
              metadata = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              metadata_.getMutableMap().put(metadata.getKey(), metadata.getMapValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.list.NestedMapDemo3.internal_static_NestedMapDemo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.list.NestedMapDemo3.internal_static_NestedMapDemo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.list.NestedMapDemo3.NestedMapDemo.class, com.google.protobuf.list.NestedMapDemo3.NestedMapDemo.Builder.class);
    }

    public static final int METADATA_FIELD_NUMBER = 1;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>>
                defaultEntry = com.google.protobuf.MapEntry.newDefaultInstance(
                        com.google.protobuf.WireFormat.FieldType.INT32,
                        0,
                        com.google.protobuf.WireFormat.FieldType.MESSAGE,
                        com.google.protobuf.MapEntry.newDefaultInstance(
                                com.google.protobuf.WireFormat.FieldType.INT32,
                                0,
                                com.google.protobuf.WireFormat.FieldType.INT32,
                                0));
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> metadata_;
    private com.google.protobuf.MapField<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>>
    internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }

    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */

    public boolean containsMetadata(
        int key) {
      
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getMetadataOrDefault(
        int key,
        java.util.Map<java.lang.Integer, java.lang.Integer> defaultValue) {
      
      java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; metadata = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getMetadataOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> entry
           : internalGetMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>>
        metadata = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, metadata);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> entry
           : internalGetMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>>
        metadata = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, metadata);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.list.NestedMapDemo3.NestedMapDemo)) {
        return super.equals(obj);
      }
      com.google.protobuf.list.NestedMapDemo3.NestedMapDemo other = (com.google.protobuf.list.NestedMapDemo3.NestedMapDemo) obj;

      boolean result = true;
      result = result && internalGetMetadata().equals(
          other.internalGetMetadata());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetMetadata().getMap().isEmpty()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetadata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.list.NestedMapDemo3.NestedMapDemo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NestedMapDemo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NestedMapDemo)
        com.google.protobuf.list.NestedMapDemo3.NestedMapDemoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.list.NestedMapDemo3.internal_static_NestedMapDemo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.list.NestedMapDemo3.internal_static_NestedMapDemo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.list.NestedMapDemo3.NestedMapDemo.class, com.google.protobuf.list.NestedMapDemo3.NestedMapDemo.Builder.class);
      }

      // Construct using com.google.protobuf.map.nested.NestedMapDemo3.NestedMapDemo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableMetadata().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.list.NestedMapDemo3.internal_static_NestedMapDemo_descriptor;
      }

      public com.google.protobuf.list.NestedMapDemo3.NestedMapDemo getDefaultInstanceForType() {
        return com.google.protobuf.list.NestedMapDemo3.NestedMapDemo.getDefaultInstance();
      }

      public com.google.protobuf.list.NestedMapDemo3.NestedMapDemo build() {
        com.google.protobuf.list.NestedMapDemo3.NestedMapDemo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.list.NestedMapDemo3.NestedMapDemo buildPartial() {
        com.google.protobuf.list.NestedMapDemo3.NestedMapDemo result = new com.google.protobuf.list.NestedMapDemo3.NestedMapDemo(this);
        int from_bitField0_ = bitField0_;
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.list.NestedMapDemo3.NestedMapDemo) {
          return mergeFrom((com.google.protobuf.list.NestedMapDemo3.NestedMapDemo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.list.NestedMapDemo3.NestedMapDemo other) {
        if (other == com.google.protobuf.list.NestedMapDemo3.NestedMapDemo.getDefaultInstance()) return this;
        internalGetMutableMetadata().mergeFrom(
            other.internalGetMetadata());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.list.NestedMapDemo3.NestedMapDemo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.list.NestedMapDemo3.NestedMapDemo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> metadata_;
      private com.google.protobuf.MapField<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>>
      internalGetMetadata() {
        if (metadata_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>>
      internalGetMutableMetadata() {
        onChanged();;
        if (metadata_ == null) {
          metadata_ = com.google.protobuf.MapField.newMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        if (!metadata_.isMutable()) {
          metadata_ = metadata_.copy();
        }
        return metadata_;
      }

      public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
      }
      /**
       * <code>map&lt;int32, int32&gt; metadata = 1;</code>
       */

      public boolean containsMetadata(
          int key) {
        
        return internalGetMetadata().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; metadata = 1;</code>
       */

      public java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> getMetadataMap() {
        return internalGetMetadata().getMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; metadata = 1;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Integer> getMetadataOrDefault(
          int key,
          java.util.Map<java.lang.Integer, java.lang.Integer> defaultValue) {
        
        java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> map =
            internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int32&gt; metadata = 1;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Integer> getMetadataOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> map =
            internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMetadata() {
        getMutableMetadata().clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; metadata = 1;</code>
       */

      public Builder removeMetadata(
          int key) {
        
        getMutableMetadata().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>>
      getMutableMetadata() {
        return internalGetMutableMetadata().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; metadata = 1;</code>
       */
      public Builder putMetadata(
          int key,
          java.util.Map<java.lang.Integer, java.lang.Integer> value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableMetadata().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; metadata = 1;</code>
       */

      public Builder putAllMetadata(
          java.util.Map<java.lang.Integer, java.util.Map<java.lang.Integer, java.lang.Integer>> values) {
        getMutableMetadata().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NestedMapDemo)
    }

    // @@protoc_insertion_point(class_scope:NestedMapDemo)
    private static final com.google.protobuf.list.NestedMapDemo3.NestedMapDemo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.list.NestedMapDemo3.NestedMapDemo();
    }

    public static com.google.protobuf.list.NestedMapDemo3.NestedMapDemo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NestedMapDemo>
        PARSER = new com.google.protobuf.AbstractParser<NestedMapDemo>() {
      public NestedMapDemo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NestedMapDemo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NestedMapDemo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NestedMapDemo> getParserForType() {
      return PARSER;
    }

    public com.google.protobuf.list.NestedMapDemo3.NestedMapDemo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestedMapDemo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NestedMapDemo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestedMapDemo_MetadataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NestedMapDemo_MetadataEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestedMapDemo_MetadataEntry_MapEntryNestedKeys_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NestedMapDemo_MetadataEntry_MapEntryNestedKeys_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024NestedMapDemo3.proto\"\224\001\n\rNestedMapDemo" +
      "\022.\n\010metadata\030\001 \003(\0132\034.NestedMapDemo.Metad" +
      "ataEntry\032S\n\rMetadataEntry\022\013\n\003key\030\001 \001(\005\022\r" +
      "\n\005value\030\002 \001(\005\032\"\n\022MapEntryNestedKeys\022\014\n\004k" +
      "ey1\030\001 \001(\005:\0028\001B \n\036com.google.protobuf.map" +
      ".nested"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NestedMapDemo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NestedMapDemo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NestedMapDemo_descriptor,
        new java.lang.String[] { "Metadata", });
    internal_static_NestedMapDemo_MetadataEntry_descriptor =
      internal_static_NestedMapDemo_descriptor.getNestedTypes().get(0);
    internal_static_NestedMapDemo_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NestedMapDemo_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_NestedMapDemo_MetadataEntry_MapEntryNestedKeys_descriptor =
      internal_static_NestedMapDemo_MetadataEntry_descriptor.getNestedTypes().get(0);
    internal_static_NestedMapDemo_MetadataEntry_MapEntryNestedKeys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NestedMapDemo_MetadataEntry_MapEntryNestedKeys_descriptor,
        new java.lang.String[] { "Key1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
