// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/decimal.proto

#ifndef PROTOBUF_google_2fprotobuf_2fdecimal_2eproto__INCLUDED
#define PROTOBUF_google_2fprotobuf_2fdecimal_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace protobuf {

// Internal implementation detail -- do not call these.
void LIBPROTOBUF_EXPORT protobuf_AddDesc_google_2fprotobuf_2fdecimal_2eproto();
void protobuf_AssignDesc_google_2fprotobuf_2fdecimal_2eproto();
void protobuf_ShutdownFile_google_2fprotobuf_2fdecimal_2eproto();

class Decimal;

// ===================================================================

class LIBPROTOBUF_EXPORT Decimal : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.protobuf.Decimal) */ {
 public:
  Decimal();
  virtual ~Decimal();

  Decimal(const Decimal& from);

  inline Decimal& operator=(const Decimal& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Decimal& default_instance();

  void UnsafeArenaSwap(Decimal* other);
  void Swap(Decimal* other);

  // implements Message ----------------------------------------------

  inline Decimal* New() const { return New(NULL); }

  Decimal* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Decimal& from);
  void MergeFrom(const Decimal& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Decimal* other);
  protected:
  explicit Decimal(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 low = 1;
  void clear_low();
  static const int kLowFieldNumber = 1;
  ::google::protobuf::uint64 low() const;
  void set_low(::google::protobuf::uint64 value);

  // optional uint32 high = 2;
  void clear_high();
  static const int kHighFieldNumber = 2;
  ::google::protobuf::uint32 high() const;
  void set_high(::google::protobuf::uint32 value);

  // optional uint32 signScale = 3;
  void clear_signscale();
  static const int kSignScaleFieldNumber = 3;
  ::google::protobuf::uint32 signscale() const;
  void set_signscale(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:google.protobuf.Decimal)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 low_;
  ::google::protobuf::uint32 high_;
  ::google::protobuf::uint32 signscale_;
  mutable int _cached_size_;
  friend void LIBPROTOBUF_EXPORT protobuf_AddDesc_google_2fprotobuf_2fdecimal_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fdecimal_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fdecimal_2eproto();

  void InitAsDefaultInstance();
  static Decimal* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Decimal

// optional uint64 low = 1;
inline void Decimal::clear_low() {
  low_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Decimal::low() const {
  // @@protoc_insertion_point(field_get:google.protobuf.Decimal.low)
  return low_;
}
inline void Decimal::set_low(::google::protobuf::uint64 value) {
  
  low_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.Decimal.low)
}

// optional uint32 high = 2;
inline void Decimal::clear_high() {
  high_ = 0u;
}
inline ::google::protobuf::uint32 Decimal::high() const {
  // @@protoc_insertion_point(field_get:google.protobuf.Decimal.high)
  return high_;
}
inline void Decimal::set_high(::google::protobuf::uint32 value) {
  
  high_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.Decimal.high)
}

// optional uint32 signScale = 3;
inline void Decimal::clear_signscale() {
  signscale_ = 0u;
}
inline ::google::protobuf::uint32 Decimal::signscale() const {
  // @@protoc_insertion_point(field_get:google.protobuf.Decimal.signScale)
  return signscale_;
}
inline void Decimal::set_signscale(::google::protobuf::uint32 value) {
  
  signscale_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.Decimal.signScale)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2fprotobuf_2fdecimal_2eproto__INCLUDED
